spring:
  profiles:
    active: prod
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/jpa_shop
      username: root
      password: root
      maximum-pool-size: 10
      minimum-idle: 3
      connection-test-query: SELECT 1
      data-source-properties:
        zeroDateTimeBehavior: convertToNull
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        default_batch_fetch_size: 1000
  jackson:
    serialization:
      fail-on-empty-beans: false
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
