spring:
  profiles:
    active: local
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/querydsl
      username: root
      password: root
      connection-test-query: SELECT 1
      data-source-properties:
        zeroDateTimeBehavior: convertToNull
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        default_batch_fetch_size: 1000
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
